apiVersion: v1
kind: Pod
metadata:
  name: centos
  namespace: default
  labels:
    app: centos
spec:
  containers:
  - image: centos
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: centos
  restartPolicy: Always
  #hostNetwork: true #测试了，不行，没有外网地址
---
kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-centos
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      targetPort: 80
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: centos
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer